Models/PetOwner.cs
using System;
using System.Collections.Generic;

namespace ProblemD.Models
{
    public class PetOwner : BaseEntity
    {
        public string Email {get;set;}
        public string Password {get;set;}
        public string PolicyNumber {get;set;}
        public DateTime EnrollmentDate {get;set;}
        public int CountryId {get;set;}
        public Country CountryOfResidence {get;set;}
        public bool Active {get;set;}
        public List<Pet> OwnedPets {get;set;}
        public PetOwner()
        {
            OwnedPets = new List<Pet>();
        }
    }
}

Controllers/PetOwnerController.cs
using System;
using ProblemD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ProblemD
{
    //This Controller is used for logic that applies to PetOwners/users, such as registration, logging in, and rendering the Dashboard
    public class PetOwnerController : Controller
    {
        //Brings access to the database through the context model
        private ProblemDContext _context;
        public PetOwnerController(ProblemDContext context)
        {
            _context = context;

        }
        [HttpGet]
        [Route("")]
        //Route to show the Login/Reg page
        public IActionResult Index()
        {
            PetOwnerRegistration regForm = new PetOwnerRegistration();
            regForm.AllCountries = _context.country.ToList(); //List of countries to populate the drop-down menu on the registration page
            ViewBag.RegForm = regForm;//Needed to bring the PetOwnerRegistration model to the registration partial page
            return View();
        }
        [HttpPost]
        [Route("RegisterError")]
        //Route to process registration
        public IActionResult Register(PetOwnerRegistration freshRegistration)
        {
            if(ModelState.IsValid)
            {
                PasswordHasher<PetOwner> hasher = new PasswordHasher<PetOwner>();
                PetOwner newPetOwner = new PetOwner{ //Transfer of ViewModel to Db Model
                    Name = freshRegistration.Name,
                    Email = freshRegistration.Email,
                    Password = freshRegistration.Password,
                    CountryId = freshRegistration.CountryId,
                    EnrollmentDate = DateTime.Now,
                    Active = true
                };
                newPetOwner.Password = hasher.HashPassword(newPetOwner ,newPetOwner.Password);
                _context.Add(newPetOwner);
                _context.SaveChanges();
                int userId = _context.petowner.Single( u => u.Email == newPetOwner.Email).Id;
                HttpContext.Session.SetInt32("activeUser", userId);
                return RedirectToAction("Dashboard");
            }
            PetOwnerRegistration regForm = new PetOwnerRegistration();//This process to re-render Index page with errors
            regForm.AllCountries = _context.country.ToList();
            ViewBag.RegForm = regForm;
            ViewBag.RegErrors = true;//Allows for registration form to appear correctly in this scenario
            return View("Index");
        }
        [HttpPost]
        [Route("LoginError")]
        //Route to process login attempt
        public IActionResult Login(PetOwnerLogin loginAttempt)
        {
            if(ModelState.IsValid)
            {
                int userId = _context.petowner.Single( u => u.Email == loginAttempt.LoginEmail).Id;
                HttpContext.Session.SetInt32("activeUser", userId);
                return RedirectToAction("Dashboard");
            }
            PetOwnerRegistration regForm = new PetOwnerRegistration();//This process to re-render Index page with errors
            regForm.AllCountries = _context.country.ToList();
            ViewBag.RegForm = regForm;
            return View("Index");
        }
        [HttpGet]
        [Route("Dashboard")]
        public IActionResult Dashboard()
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckForActiveUser(activeId);
            if(isValid == false)
            {
                return RedirectToAction("Index");
            }
            PetValidation newPetModel = new PetValidation();
            newPetModel.AllBreeds = _context.breed.OrderByDescending( b => b.Name ).ToList();
            ViewBag.NewPetModel = newPetModel;//Model placed in ViewBag to allow for form to appear on rendered partial
            PetOwner activeUser = _context.petowner.Include( o => o.CountryOfResidence ).Include( o => o.OwnedPets ).ThenInclude( p => p.Breed ).Single( o => o.Id == (int)activeId);
            return View(activeUser);
        }
        [HttpGet]
        [Route("{change}Policy/{id}")]
        public IActionResult CancelPolicy(string change, int id)
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckIfUserAuthorized(activeId, id);
            if(isValid == false)
            {
                //Redirected to Logout as user may be malicious
                return RedirectToAction("Logout");
            }
            PetOwner activeUser = _context.petowner.Include( o => o.OwnedPets ).Single( o => o.Id == id);
            //Switch case allows one route/method to handle different yet similar logic as needed
            switch(change)
            {
                case "Cancel":
                    activeUser.Active = false;
                    foreach(Pet pet in activeUser.OwnedPets)
                    {
                        pet.Active = false;
                    }
                    break;
                case "Activate":
                    activeUser.Active = true;
                    break;
            }
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        [HttpGet]
        [Route("/logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("/");
        }
    }
}

Views/PetOwner/Dashboard.cshtml
@model PetOwner
<script src="~/js/script.js" language="javascript" type="text/javascript"></script>
<h1>Welcome, @Model.Name!</h1>
<a href="/logout">Logout</a>
<h3>Policy Number: @Model.PolicyNumber</h3>
@if(Model.Active == true)
{
    <h3>Status: Active &nbsp; <button class="btn btn-default" onclick="location.href='/CancelPolicy/@Model.Id'">Cancel Policy</button></h3>
    
}
else
{
    <h3>Status: Inactive &nbsp; <button class="btn btn-default" onclick="location.href='/ActivatePolicy/@Model.Id'">Activate Policy</button></h3>
    
}

<h4>Country of Residence: @Model.CountryOfResidence.Name</h4>

<h3>Pets Currently Covered: &nbsp; <button class="btn btn-default" id="ShowNewPetButton">Add a Pet!</button></h3>
<table class="table table-striped table-bordered">
    <thead>
        <th>Name</th>
        <th>Birthday</th>
        <th>Breed</th>
        <th>Status</th>
        <th>Actions</th>
    </thead>
    <tbody>
        @foreach(Pet pet in @Model.OwnedPets)
        {
            <tr>
                <td>@pet.Name</td>
                <td>@pet.DateOfBirth.ToString("MMMM d, yyyy")</td>
                <td>@pet.Breed.Name</td>
                <td>
                    @if(@pet.Active == true)
                    {
                        <p>Active</p>
                    }
                    else
                    {
                        <p>Inactive</p>
                    }
                </td>
                <td>
                    @if(@pet.Active == true)
                    {
                        <button class="btn btn-default" onclick="location.href='/CancelPet/@pet.Id'">Remove from Policy</button>
                    }
                    else
                    {
                        if(Model.Active == true)
                        {
                            <button class="btn btn-default" onclick="location.href='/ActivatePet/@pet.Id'">Activate Policy</button>
                        }
                        
                    }
                    &nbsp;
                    <button class="btn btn-default" onclick="location.href='/TransferPet/@pet.Id'">Transfer to another owner</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="NewPetForm" style="display: none">
    @Html.Partial("~/Views/Pet/NewPet.cshtml", (PetValidation)@ViewBag.NewPetModel)
</div>

Views/PetOwner/Index.cshtml
@model PetOwnerLogin
<script src="~/js/script.js" language="javascript" type="text/javascript">
</script>
<h1>Welcome to PetInsuranceCo!</h1>
<h3>Please Login</h3>
<form asp-action="Login" asp-controller="PetOwner" method="POST">
    <table class="table">
        <tr class="form-group">
            <td><label asp-for="LoginEmail"></label></td>
            <td><input asp-for="LoginEmail" class="form-control"></td>
            <td><span asp-validation-for="LoginEmail"></span></td>
        </tr>
        <tr class="form-group">
            <td><label asp-for="LoginPassword"></label></td>
            <td><input type="password" asp-for="LoginPassword" class="form-control"></td>
            <td><span asp-validation-for="LoginPassword"></span></td>
        </tr>
    </table>
    <input class="btn btn-default" type="Submit" value="Login">
</form>
<hr>
<button class="btn btn-default" id="ShowRegisterButton">New? Click here to Register!</button>
<hr>
<div id="RegisterForm" style="display: none">
    @Html.Partial("Register", (PetOwnerRegistration)@ViewBag.RegForm)
</div>

Views/PetOwner/Register.cshtml
@model PetOwnerRegistration

<script>
    var errors = "True"
    if(errors == "@ViewBag.RegErrors")
    {
        
        $('#ShowRegisterButton').html("Already Registered? Just Login above!");
        $('#RegisterForm').show();
    }
</script>
<form asp-action="Register" asp-controller="PetOwner" method="POST">
    <table class="table">
        <tr class="form-group">
            <td><label asp-for="Name"></label></td>
            <td><input asp-for="Name" class="form-control"></td>
            <td><span asp-validation-for="Name"></span></td>
        </tr>
        <tr class="form-group">
            <td><label asp-for="CountryId"></label></td>
            <td>
                <select asp-for="CountryId" class="form-control">
                    @foreach(var country in @Model.AllCountries)
                    {
                        <option value="@country.Id">@country.Name</option>
                    }
                </select>
            </td>
            <td><span asp-validation-for="CountryId"></span></td>
        </tr>
        <tr class="form-group">
            <td><label asp-for="Email"></label></td>
            <td><input asp-for="Email" class="form-control"></td>
            <td><span asp-validation-for="Email"></span></td>
        </tr>
        <tr class="form-group">
            <td><label asp-for="Password"></label></td>
            <td><input asp-for="Password" type="password" class="form-control"></td>
            <td><span asp-validation-for="Password"></span></td>
        </tr>
        <tr class="form-group">
            <td><label asp-for="PasswordConfirmation"></label></td>
            <td><input asp-for="PasswordConfirmation" type="password" class="form-control"></td>
            <td><span asp-validation-for="PasswordConfirmation"></span></td>
        </tr>
    </table>
    <input class="btn btn-default" type="Submit" value="Register">
</form>