Models/Pet.cs
using System;
using System.Collections.Generic;

namespace ProblemD.Models
{
    public class Pet : BaseEntity
    {
        public DateTime DateOfBirth {get;set;}
        public int PetOwnerId {get;set;}
        public PetOwner Owner {get;set;}
        public int BreedId {get;set;}
        public Breed Breed {get;set;}
        public bool Active {get;set;}
    }
}

Controllers/PetController.cs
using System;
using ProblemD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ProblemD
{
    public class PetController : Controller
    {
        private ProblemDContext _context;
        public PetController(ProblemDContext context)
        {
            _context = context;
        }
        [HttpPost]
        [Route("Dashboard")]
        //Route to process new pet and maybe breed creation
        public IActionResult NewPet(PetValidation newPotentialPet)
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckForActiveUser(activeId);
            if(isValid == false)
            {
                return RedirectToAction("Index", "PetOwner");
            }
            if(ModelState.IsValid)
            {
                if(newPotentialPet.BreedId == 0)
                {
                    var shouldBeNull = _context.breed.SingleOrDefault( b => b.Name == newPotentialPet.NewBreedName);
                    if(shouldBeNull != null)
                    {
                        //Logic for this did not seem to work as a custom validation, //TODO//
                        ViewBag.Error = "There is already a breed by that name";
                        return View("Dashboard");
                    }
                    Breed newBreed = new Breed{
                        Name = newPotentialPet.NewBreedName
                    };
                    _context.Add(newBreed);
                    _context.SaveChanges();
                    int newBreedId = _context.breed.Single( b => b.Name == newPotentialPet.NewBreedName).Id;
                    newPotentialPet.BreedId = newBreedId;
                }
                Pet newPet = new Pet{//Transfer to DB Model
                    Name = newPotentialPet.PetName,
                    BreedId = newPotentialPet.BreedId,
                    PetOwnerId = (int)activeId,
                    DateOfBirth = newPotentialPet.DateOfBirth,
                    Active = true
                };
                _context.Add(newPet);
                _context.SaveChanges();
                return RedirectToAction("Dashboard", "PetOwner");
            }
            return View("Dashboard");
        }
        [HttpGet]
        [Route("{change}Pet/{id}")]
        public IActionResult CancelPetPolicy(string change, int id)
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckActiveUserVsPet(activeId, id, _context);
            if(isValid == false)
            {
                //Redirected to Logout as user may be malicious
                return RedirectToAction("Logout", "PetOwner");
            }
            var changingPet = _context.pet.SingleOrDefault( p => p.Id == id);
            //Switch case allows one route/method to handle different yet similar logic as needed
            switch(change)
            {
                case "Transfer":
                    return RedirectToAction("Transfer", new{ id = id });
                case "Cancel":
                    changingPet.Active = false;
                    break;
                case "Activate":
                    changingPet.Active = true;
                    break;
            }
            _context.SaveChanges();
            return RedirectToAction("Dashboard", "PetOwner");
        }
        [HttpGet]
        [Route("Pet/Transfer/{id}")]
        public IActionResult Transfer(int id)
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckActiveUserVsPet(activeId, id, _context);
            if(isValid == false)
            {
                //Redirected to Logout as user may be malicious
                return RedirectToAction("Logout", "PetOwner");
            }
            var transferPet = _context.pet.SingleOrDefault( p => p.Id == id);
            TransferOwner transfer = new TransferOwner{
                PetToBeTransferred = (Pet)transferPet,
                CurrentOwner = _context.petowner.SingleOrDefault( o => o.Id == (int)activeId)
            };
            return View(transfer);
        }
        [HttpPost]
        [Route("Transfer/{petId}/From/{ownerId}")]
        public IActionResult ProcessTransfer(TransferOwner transfer, int petId, int ownerId)
        {
            int? activeId = HttpContext.Session.GetInt32("activeUser");
            bool isValid = SecurityCheck.CheckUserCanTransfer(activeId, petId, ownerId, _context);
            if(!isValid)
            {
                //Redirected to Logout as user may be malicious
                return RedirectToAction("Logout", "PetOwner");
            }
            var transferPet = _context.pet.SingleOrDefault( p => p.Id == petId);
            if(ModelState.IsValid)
            {
                int newOwnerId = _context.petowner.Single( o => o.Email == transfer.Email ).Id;
                transferPet.PetOwnerId = newOwnerId;
                transferPet.Active = false;
                _context.SaveChanges();
                return RedirectToAction("Dashboard", "PetOwner");
            }
            transfer.PetToBeTransferred = (Pet)transferPet;
            transfer.CurrentOwner = _context.petowner.SingleOrDefault( o => o.Id == (int)activeId);
            transfer.Email = "";
            return View("Transfer",transfer);
        }
    }
}

Views/Pet/NewPet.cshtml
@model PetValidation
<form asp-action="NewPet" asp-controller="Pet" method="POST">
    <table class="table">
        <tr>
            <td><label asp-for="PetName"></label></td>
            <td><input asp-for="PetName"></td>
            <td><span asp-validation-for="PetName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="DateOfBirth"></label></td>
            <td><input asp-for="DateOfBirth" type="date"></td>
            <td><span asp-validation-for="DateOfBirth"></span></td>
        </tr>
        <tr>
            <td><label asp-for="BreedId"></label></td>
            <td>
                <select asp-for="BreedId" id="BreedSelect">
                    @{int i = 0;}
                    <option value="0" id="NewBreedOption">Add New Breed!</option>
                    @foreach(Breed breed in @Model.AllBreeds)
                        {
                            <option selected value="@breed.Id">@breed.Name</option>
                        }
                        
                </select>
            </td>
            <td><span asp-validation-for="BreedId"></span></td>
        </tr>
        <tr id="NewBreedForm" style="display: none">
            <td><label asp-for="NewBreedName"></label></td>
            <td><input asp-for="NewBreedName"></td>
            <td><span asp-validation-for="NewBreedName">@ViewBag.Error</span></td>
        </tr>
    </table>
    <input class="btn btn-default" type="submit" value="Register New Pet">
</form>

Views/Pet/Transfer.cshtml
@model TransferOwner
<form action="/Transfer/@Model.PetToBeTransferred.Id/From/@Model.CurrentOwner.Id" method="POST">
    <h4>Please enter the email of the Pet Owner that @Model.PetToBeTransferred.Name will be transferred to:</h4>
    <p>*Note: Pet's status will be in-active until approved by their newly listed owner*</p>
    <input asp-for="Email"><span asp-validation-for="Email"></span>
    <input type="submit" value="Transfer">
</form>